spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true

  data:
    redis:
      host: 172.30.1.82
      port: 6379
      password: lldj123414
      database: 1




