spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(caq/+9P8gm2xwvxAc6bryGylgJEX19QHmuL3umll+NyiG7ggOoug5uWyGDTQzBd1YG4YpRK/PVvYFt2zHM0bYrLSPIg4kIo3fpJFJnlWD3bzjY1UXSuTBuhLM3r4JgfuRlsfAb9tWG7E+KSIe1HQWedUAT4vbT9IYxskAIZVkCFqWIS8v3EChQ==)
    username: ENC(feciTQh5rLQ2dmTa1Z/A9g==)
    password: ENC(lZ30TkUte7l7K/5PAiHp3g==)
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 200
        default_lazy_load_no_trans: true
    defer-datasource-initialization: true

decorator:
  datasource:
    p6spy:
      enable-logging: false
custom:
  site:
    baseUrl: www.yhss.site


